#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE_BUILTIN true

#define CLASS_HASHTABLE_SIZE 64
#define TRAIT_IMPL_HASHTABLE_SIZE 8
#define METHODS_IMPL_HASHTABLE_SIZE 16

#define MAX_TRAITS 32
#define MAX_METHODS_PER_TRAITS 4
#define MAX_PARAMS_PER_METHODS 4

#endif //CONFIG_H
