#ifndef CONFIG_H
#define CONFIG_H

#define ENABLE_BUILTIN true

#define MAX_TRAITS 32
#define MAX_CLASSES 32
#define MAX_TRAIT_IMPLS 4

#define MAX_METHODS_PER_TRAITS 4
#define MAX_PARAMS_PER_METHODS 4

#endif //CONFIG_H
